### Task 2

In [22]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [24]:
url = 'https://politifact.com/factchecks'
result = requests.get(url)
content = result.text

soup = BeautifulSoup(content,'html.parser')

author = soup.find_all('a',class_='m-statement__name')
quote = soup.find_all('div',class_='m-statement__quote')
date = soup.find_all('footer')
authors = []
quotes = []
links = []
dates = []


for i,j,k in zip(author,quote,date):
    authors.append(i.text.strip())
    quotes.append(j.text.strip())
    links.append('https://politifact.com'+j.find('a')['href'])
    dates.append(k.text.split('•')[-1].strip())

df = pd.DataFrame({'Author':authors,'Quote':quotes,'Link':links,'Date':dates})
df

,Author,Quote,Link,Date
0,X posts,"Video shows U.S. Rep. Byron Donalds saying, “I...",https://politifact.com/factchecks/2026/may/15/...,"May 15, 2026"
1,X posts,An American passenger on the cruise ship invol...,https://politifact.com/factchecks/2026/may/14/...,"May 14, 2026"
2,Kathy Castor,“Florida is the only state in the nation kicki...,https://politifact.com/factchecks/2026/may/14/...,"May 14, 2026"
3,Vivek Ramaswamy,"In 2020, “Amy Acton called off Ohio’s election...",https://politifact.com/factchecks/2026/may/13/...,"May 13, 2026"
4,TikTok posts,Imágenes muestran a personas “infectadas con H...,https://politifact.com/factchecks/2026/may/13/...,"May 13, 2026"
5,Christine Quinn,"“Today, there are more children sleeping in Ne...",https://politifact.com/factchecks/2026/may/11/...,"May 11, 2026"
6,Nicholas Langworthy,“The average IRS tax refund is up 11% compared...,https://politifact.com/factchecks/2026/may/11/...,"May 11, 2026"
7,Donald Trump,Gasoline prices have “come down very substanti...,https://politifact.com/factchecks/2026/may/08/...,"May 8, 2026"
8,Byron Donalds,Congress passed the 1965 Voting Rights Act bec...,https://politifact.com/factchecks/2026/may/08/...,"May 8, 2026"
9,Marcy Kaptur,Republicans “want you to pay $1 Billion for a ...,https://politifact.com/factchecks/2026/may/08/...,"May 8, 2026"
10,Liz Krueger,Proposed data centers in New York state would ...,https://politifact.com/factchecks/2026/may/07/...,"May 7, 2026"
11,X posts,“California only has ‘enough’ oil and gas supp...,https://politifact.com/factchecks/2026/may/07/...,"May 7, 2026"
12,Donald Trump,"“Consumer confidence is way up.""",https://politifact.com/factchecks/2026/may/06/...,"May 6, 2026"
13,Sam Sutton,"From January 2025 to January 2026, “hate crime...",https://politifact.com/factchecks/2026/may/05/...,"May 5, 2026"
14,Fentrice Driskell,"“Under federal law, you cannot engage in parti...",https://politifact.com/factchecks/2026/may/01/...,"May 1, 2026"
15,Instagram posts,Imagen muestra que “950 inmigrantes derrumbaro...,https://politifact.com/factchecks/2026/apr/30/...,"April 30, 2026"
16,Bernie Sanders,“As a result of the 'Big Beautiful Bill' 15 mi...,https://politifact.com/factchecks/2026/apr/30/...,"April 30, 2026"
17,Tim Scott,“Secret Service remains unpaid” during the par...,https://politifact.com/factchecks/2026/apr/29/...,"April 29, 2026"
18,Pine Tree Results PAC,“Graham Platner blames Maine’s women for getti...,https://politifact.com/factchecks/2026/apr/29/...,"April 29, 2026"
19,Social Media,Video shows “unedited raw security footage” of...,https://politifact.com/factchecks/2026/apr/29/...,"April 29, 2026"
20,Donald Trump,“We are right now producing more oil than Saud...,https://politifact.com/factchecks/2026/apr/29/...,"April 29, 2026"
21,Ron DeSantis,"Since the 2020 census, Florida has ""moved from...",https://politifact.com/factchecks/2026/apr/29/...,"April 29, 2026"
22,Social Media,"“Tras el atentado a Trump”, en la cena de corr...",https://politifact.com/factchecks/2026/apr/28/...,"April 28, 2026"
23,Jay Collins,"U.S. Rep. Byron Donalds voted ""against three p...",https://politifact.com/factchecks/2026/apr/23/...,"April 23, 2026"
24,Robert F. Kennedy Jr.,"""There's two ways of calculating percentage"" d...",https://politifact.com/factchecks/2026/apr/23/...,"April 23, 2026"
25,Joe Rogan,"“With one dose of ibogaine, more than 80% of p...",https://politifact.com/factchecks/2026/apr/22/...,"April 22, 2026"
26,X posts,“Newly released FOIA door logs show that forme...,https://politifact.com/factchecks/2026/apr/22/...,"April 22, 2026"
27,Chris Wright,Solar and wind have not reached “3% of global ...,https://politifact.com/factchecks/2026/apr/22/...,"April 22, 2026"
28,Facebook posts,Video shows President Donald Trump at the Walt...,https://politifact.com/factchecks/2026/apr/21/...,"April 21, 2026"
29,Democratic National Committee,President Donald Trump's proposed 2027 militar...,https://politifact.com/factchecks/2026/apr/20/...,"April 20, 2026"

### Access multiple pages

In [25]:
authors = []
quotes = []
links = []
dates = []
for i in range(0,5):
    url = f'https://politifact.com/factchecks/?page={i}'

    result = requests.get(url)
    content = result.text
    
    soup = BeautifulSoup(content,'html.parser')
    
    author = soup.find_all('a',class_='m-statement__name')
    quote = soup.find_all('div',class_='m-statement__quote')
    date = soup.find_all('footer')
    
    for i,j,k in zip(author,quote,date):
        authors.append(i.text.strip())
        quotes.append(j.text.strip())
        links.append('https://politifact.com'+j.find('a')['href'])
        dates.append(k.text.split('•')[-1].strip())
    
df = pd.DataFrame({'Author':authors,'Quote':quotes,'Link':links,'Date':dates})
df

,Author,Quote,Link,Date
0,X posts,"Video shows U.S. Rep. Byron Donalds saying, “I...",https://politifact.com/factchecks/2026/may/15/...,"May 15, 2026"
1,X posts,An American passenger on the cruise ship invol...,https://politifact.com/factchecks/2026/may/14/...,"May 14, 2026"
2,Kathy Castor,“Florida is the only state in the nation kicki...,https://politifact.com/factchecks/2026/may/14/...,"May 14, 2026"
3,Vivek Ramaswamy,"In 2020, “Amy Acton called off Ohio’s election...",https://politifact.com/factchecks/2026/may/13/...,"May 13, 2026"
4,TikTok posts,Imágenes muestran a personas “infectadas con H...,https://politifact.com/factchecks/2026/may/13/...,"May 13, 2026"
...,...,...,...,...
115,Social Media,A letter sent to postal service employees abou...,https://politifact.com/factchecks/2026/jan/15/...,"January 15, 2026"
116,Mehmet Oz,"“By federal law, if you sign someone up for Me...",https://politifact.com/factchecks/2026/jan/14/...,"January 14, 2026"
117,Donald Trump,"""If we stop this fraud, this massive fraud, we...",https://politifact.com/factchecks/2026/jan/13/...,"January 13, 2026"
118,Social Media,A document shows Minnesota shooting victim Ren...,https://politifact.com/factchecks/2026/jan/12/...,"January 12, 2026"
119,Donald Trump,Credit card companies would be “in violation o...,https://politifact.com/factchecks/2026/jan/12/...,"January 12, 2026"

## How to access html file in exam

In [33]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(open('politifact.html','r',encoding='utf-8'))

### Task 3

In [49]:
soup = BeautifulSoup(open('top250.html','r',encoding='utf-8'))

title = soup.find_all('td',class_='titleColumn')
rating = soup.find_all('td',class_='ratingColumn imdbRating')
titles = []
years = []
ratings = []

for i,j in zip(title,rating):
    titles.append(i.find('a',href=True).text)
    years.append(i.find('span').text[1:-1])
    ratings.append(j.text.strip())

df = pd.DataFrame({'Title':titles,'Year':years,'Rating':ratings})
df

                        Title  Year Rating
0    The Shawshank Redemption  1994    9.2
1               The Godfather  1972    9.2
2             The Dark Knight  2008    9.0
3       The Godfather Part II  1974    9.0
4                12 Angry Men  1957    9.0
..                        ...   ...    ...
245                  The Help  2011    8.0
246             Life of Brian  1979    8.0
247            The Iron Giant  1999    8.0
248                   Aladdin  1992    8.0
249        Dances with Wolves  1990    8.0

[250 rows x 3 columns]

### Task 4

In [107]:
soup = BeautifulSoup(open('flipkart.html','r',encoding='utf-8'))

name = soup.find_all('div',class_='KzDlHZ')
ram = soup.find_all('div',class_='_6NESgJ')
rating = soup.find_all('div',class_='XQDdHH')
price = soup.find_all('div',class_='Nx9bqj _4b5DiR')
names = []
colors = []
RAM = []
ROM = []
ratings = []
prices = []

for i,j,k,l in zip(name,ram,rating,price):
    names.append(i.text.split('(')[0])
    colors.append(i.text.split('(')[1].split(',')[0])
    ROM.append(i.text.split('(')[1].split(',')[1][1:-1])
    RAM.append(j.find('li').text.split('|')[0][0:-5])
    ratings.append(k.text)
    prices.append(l.text)

df = pd.DataFrame({'Name':names,'Color':colors,'RAM':RAM,'ROM':ROM,'Rating':ratings,'Price':prices})
df

,Name,Color,RAM,ROM,Rating,Price
0,realme C61,Marble Black,6 GB,128 GB,4.4,"₹8,199"
1,realme C61,Safari Green,6 GB,128 GB,4.4,"₹8,199"
2,realme C63 5G Charger in the Box,Forest Green,6 GB,128 GB,4.5,"₹10,999"
3,realme P3x 5G,Lunar Silver,6 GB,128 GB,4.5,"₹13,999"
4,realme C61,Marble Black,4 GB,64 GB,4.3,"₹7,699"
5,realme P2 Pro 5G,Parrot Green,12 GB,512 GB,4.4,"₹20,999"
6,realme Narzo N61,Marble Black,4 GB,64 GB,4.3,"₹7,380"
7,realme Narzo N61,Vyage Blue,4 GB,64 GB,4.3,"₹7,335"
8,realme C61,Safari Green,4 GB,64 GB,4.3,"₹7,699"
9,realme P3x 5G,Midnight Blue,6 GB,128 GB,4.5,"₹13,999"
10,realme 14x 5G,Jewel Red,6 GB,128 GB,4.4,"₹14,999"
11,realme P3 5G,Nebula Pink,6 GB,128 GB,4.4,"₹15,999"
12,realme P2 Pro 5G,Parrot Green,8 GB,128 GB,4.4,"₹17,999"
13,realme P2 Pro 5G,Parrot Green,12 GB,256 GB,4.4,"₹19,999"
14,realme P3 5G,Space Silver,8 GB,256 GB,4.4,"₹18,499"
15,realme 14 Pro 5G,Suede Grey,8 GB,128 GB,4.4,"₹24,999"
16,realme Narzo N65 5G,Ambr Gold,6 GB,128 GB,4.3,"₹12,448"
17,realme 13 Pro 5G,Monet Gold,12 GB,512 GB,4.3,"₹26,999"
18,realme 14 Pro+ 5G,Suede Grey,12 GB,512 GB,4.4,"₹37,999"
19,realme 14x 5G,Crystal Black,6 GB,128 GB,4.4,"₹14,999"
20,realme P3 5G,Space Silver,6 GB,128 GB,4.4,"₹15,999"
21,realme 13 Pro+ 5G,Monet Purple,8 GB,256 GB,4.4,"₹25,999"
22,realme Narzo N65 5G,Deep Green,4 GB,128 GB,4.3,"₹10,471"
23,realme 14 Pro 5G,Jaipur Pink,8 GB,128 GB,4.4,"₹24,999"