In [8]:
API_Key = '8a1c4f528052ff9f2e1b1afe26e4cb8b'
import requests,json
import pandas as pd

In [9]:
def get_coordinates():
    # api_key = input('Enter API Key: ')
    api_key = API_Key
    city = input('Enter City Name: ')
    request_url = f'http://api.openweathermap.org/geo/1.0/direct?q={city}&appid={api_key}'
    response = requests.get(request_url)
    coordinates = response.json()
    # print(json.dumps(coordinates,indent=5))
    lattitude = coordinates[0]['lat']
    longitude = coordinates[0]['lon']
    return lattitude,longitude,city

lat,lon,city = get_coordinates()

print(city)
print('--------')
print('Lattitude: ',lat)
print('Logitude: ',lon)

Enter City Name:  Ahmedabad

Ahmedabad
--------
Lattitude:  23.0215374
Logitude:  72.5800568

In [10]:
def get_air_pollution():
    api_key = API_Key
    url = f'http://api.openweathermap.org/data/2.5/air_pollution?lat={lat}&lon={lon}&appid={API_Key}'
    response = requests.get(url)

    pollution = response.json()

    a = pollution['list'][0]['main']['aqi']

    if(a==1):
        print('GOOD')
    if(a==2):
        print('FAIR')
    if(a==3):
        print('MODERATE')
    if(a==4):
        print('POOR')
    if(a==5):
        print('VERY POOR')

get_air_pollution()

FAIR

In [11]:
dt = []
des = []
temp = []
pressure = []
hum = []
visibility = []
ws = []

def forecast5():
    url = f'https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={API_Key}'
    response = requests.get(url)
    
    f = response.json()
    # print(json.dumps(f,indent=5))

    for i in range(0,40):
        dt.append(f['list'][i]['dt_txt'])
        des.append(f['list'][i]['weather'][0]['description'])
        temp.append(f['list'][i]['main']['temp'])
        pressure.append(f['list'][i]['main']['pressure'])
        hum.append(f['list'][i]['main']['humidity'])
        visibility.append(f['list'][i]['visibility'])
        ws.append(f['list'][i]['wind']['speed'])
forecast5()

df = pd.DataFrame({'Date':dt,'Description':des,'Temperature':temp,'Pressure':pressure,'Humidity':hum,'Visibility':visibility,'Wind Speed':ws})
df

,Date,Description,Temperature,Pressure,Humidity,Visibility,Wind Speed
0,2026-05-26 09:00:00,clear sky,309.19,1004,34,10000,4.87
1,2026-05-26 12:00:00,clear sky,311.46,1004,28,10000,5.66
2,2026-05-26 15:00:00,clear sky,308.62,1005,38,10000,5.12
3,2026-05-26 18:00:00,clear sky,305.21,1007,57,10000,2.92
4,2026-05-26 21:00:00,clear sky,303.21,1006,62,10000,3.95
5,2026-05-27 00:00:00,clear sky,302.65,1007,62,10000,4.78
6,2026-05-27 03:00:00,clear sky,305.03,1009,50,10000,5.00
7,2026-05-27 06:00:00,clear sky,311.79,1008,25,10000,5.14
8,2026-05-27 09:00:00,clear sky,316.06,1005,15,10000,5.63
9,2026-05-27 12:00:00,clear sky,316.33,1003,14,10000,6.11
10,2026-05-27 15:00:00,clear sky,306.80,1006,50,10000,5.78
11,2026-05-27 18:00:00,clear sky,305.67,1008,50,10000,2.79
12,2026-05-27 21:00:00,clear sky,302.94,1006,63,10000,4.68
13,2026-05-28 00:00:00,clear sky,302.78,1007,60,10000,5.03
14,2026-05-28 03:00:00,clear sky,304.97,1009,52,10000,5.91
15,2026-05-28 06:00:00,clear sky,312.36,1007,23,10000,6.11
16,2026-05-28 09:00:00,clear sky,317.27,1004,13,10000,6.45
17,2026-05-28 12:00:00,clear sky,317.03,1002,13,10000,6.80
18,2026-05-28 15:00:00,clear sky,307.78,1005,40,10000,4.84
19,2026-05-28 18:00:00,clear sky,304.78,1006,46,10000,4.48
20,2026-05-28 21:00:00,clear sky,304.13,1006,54,10000,5.56
21,2026-05-29 00:00:00,clear sky,302.30,1007,66,10000,5.40
22,2026-05-29 03:00:00,clear sky,304.68,1008,53,10000,7.25
23,2026-05-29 06:00:00,clear sky,311.77,1006,26,10000,7.62
24,2026-05-29 09:00:00,clear sky,315.95,1003,17,10000,8.09
25,2026-05-29 12:00:00,clear sky,315.81,1001,17,10000,7.96
26,2026-05-29 15:00:00,clear sky,307.67,1003,36,10000,8.32
27,2026-05-29 18:00:00,clear sky,305.89,1003,46,10000,5.63
28,2026-05-29 21:00:00,clear sky,303.03,1003,61,10000,6.87
29,2026-05-30 00:00:00,clear sky,301.72,1004,70,10000,6.54
30,2026-05-30 03:00:00,clear sky,304.61,1005,56,10000,7.80
31,2026-05-30 06:00:00,clear sky,311.27,1003,32,10000,8.71
32,2026-05-30 09:00:00,clear sky,315.77,1000,21,10000,8.71
33,2026-05-30 12:00:00,clear sky,314.85,999,22,10000,8.73
34,2026-05-30 15:00:00,clear sky,310.05,1001,34,10000,7.02
35,2026-05-30 18:00:00,clear sky,305.27,1003,53,10000,7.99
36,2026-05-30 21:00:00,clear sky,302.99,1003,67,10000,6.17
37,2026-05-31 00:00:00,clear sky,302.18,1003,71,10000,5.30
38,2026-05-31 03:00:00,broken clouds,304.32,1005,58,10000,6.94
39,2026-05-31 06:00:00,scattered clouds,310.51,1004,35,10000,6.24

In [12]:
API_Key = '0jzGiSbnVqPqMHqD3Z3eoIMGPJu6T85bFheavYvd'

In [15]:
dt = []
u = []

def nasa_image():
    api_key = API_Key
    url = f'https://api.nasa.gov/planetary/apod?api_key={api_key}&count=10'
    response = requests.get(url)
    c = response.json()
    # print(json.dumps(c,indent=5))

    for i in c:
        dt.append(i['date'])
        u.append(i['url'])
nasa_image()
df = pd.DataFrame({'Date':dt,'URL':u})
df

         Date                                                URL
0  2026-03-03  https://apod.nasa.gov/apod/image/2603/FlyingNo...
1  1996-07-21   https://apod.nasa.gov/apod/image/lm_apollo11.gif
2  2017-08-18  https://apod.nasa.gov/apod/image/1708/Perseids...
3  2024-11-14  https://apod.nasa.gov/apod/image/2411/IC348_B3...
4  1995-08-31    https://apod.nasa.gov/apod/image/moon_rosat.gif
5  2025-10-11  https://apod.nasa.gov/apod/image/2510/iss059e0...
6  2003-07-11  https://apod.nasa.gov/apod/image/0307/ngc1068_...
7  2012-09-13  https://apod.nasa.gov/apod/image/1209/cocoonla...
8  2012-11-01  https://apod.nasa.gov/apod/image/1211/rigelwit...
9  2013-06-21  https://apod.nasa.gov/apod/image/1306/sequence...